# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :deployTestApp do |options|
    begin
      gradle(task: "clean bundle", build_type: 'release')

      puts "AABs: #{Actions.lane_context[SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS]}"
      puts "AAB: #{Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"

      upload_to_play_store(
        json_key: "../json_key_file.json",
        package_name: "mwaris.dev.test",
        track: 'internal',
        aab: "#{Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        rollout: "1.0"
      )

    rescue => exception
      on_error(exception)
    end
  end

end

### Methods

def on_error(exception)
   puts exception.to_s
end